spring:
  application:
    name: rabbitmq-consumer1
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: localhost
    publisher-confirms: true
    virtual-host: /

server:
  port: 8004
